//定义 gitlab的凭证ID

def git_auth = "8a643656-f20c-4837-a6bb-f3f5074c95ad"
               

//定义 gitlab的url地址
def git_url = "git@192.168.110.100:itheima_group/tensquare_back.git"
           
node {
  stage('拉取代码') {
	  checkout scmGit(branches: [[name: "*/${branch}"]], 
	                  extensions: [], userRemoteConfigs: [[credentialsId: "${git_auth}", url: "${git_url}"]])
		   										 
  }
  
  stage('代码审查'){
      //定义当前Jenkins的SonarQubeScanner工具
      def scannerHome = tool 'sonar-scanner'
      //引用当前JenkinsSonarQube环境
      withSonarQubeEnv('sonarqube'){
         sh """
             cd tensquare_parent/${project_name}
             
             ${scannerHome}/bin/sonar-scanner
             
            """
      }
  }
  
  stage('编译，安装公共子工程'){
      sh "mvn -f tensquare_parent/tensquare_common clean install"
  
  }
  
  stage('编译，打包微服务工程'){
      sh "mvn -f tensquare_parent/${project_name} clean package"
  
  }
      
}