pipeline {
    agent any

    stages {
        stage('pull code ') {
            steps {
               checkout scmGit(branches: [[name: '*/${branch}']], 
               extensions: [],
               userRemoteConfigs: [[credentialsId: '8a643656-f20c-4837-a6bb-f3f5074c95ad', 
                                    url: 'git@192.168.110.100:itheima_group/web_demo.git']])
            }
        }
        
        stage('code checking') {
	         steps {
	
	            script {
	                 //引入SonarQubeScanner工具
	                scannerHome = tool 'sonar-scanner'
	            }
	            //引入SonarQube的服务器环境
	            withSonarQubeEnv('sonarqube') {
	                sh "${scannerHome}/bin/sonar-scanner　-Dsonar.projectKey=develop -Dsonar.sources=."
	            }
	         }
         }
        
        stage('build project ') {
            steps {
              sh '''cd /var/lib/jenkins/workspace/web_demo_pipeline/web_demo/
              mvn clean package'''
            }
        }
        stage('publish project ') {
            steps {
                deploy adapters: [tomcat7(credentialsId: 'beadfff4-fe30-4375-b0ac-ee4215f80349', 
                                  path: '',
                                  url: 'http://192.168.110.204:8080')],contextPath: null, war: '**/*.war'
             
            }
        }
     }   
    post {
         always {
            emailext(
               subject: '构建通知：${PROJECT_NAME} - Build # ${BUILD_NUMBER} - ${BUILD_STATUS}!',
               body: '${FILE,path="email.html"}',
               to: 'yuanlove1116@yahoo.co.jp'
            )
         }
    }

}
