package com.bjpowernode.crm.settings.mapper;

import java.util.List;

import com.bjpowernode.crm.settings.domain.DicValue;

public interface DicValueMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tbl_dic_value
	 *
	 * @mbg.generated Sun Mar 24 23:53:46 JST 2024
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tbl_dic_value
	 *
	 * @mbg.generated Sun Mar 24 23:53:46 JST 2024
	 */
	int insert(DicValue row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tbl_dic_value
	 *
	 * @mbg.generated Sun Mar 24 23:53:46 JST 2024
	 */
	int insertSelective(DicValue row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tbl_dic_value
	 *
	 * @mbg.generated Sun Mar 24 23:53:46 JST 2024
	 */
	DicValue selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tbl_dic_value
	 *
	 * @mbg.generated Sun Mar 24 23:53:46 JST 2024
	 */
	int updateByPrimaryKeySelective(DicValue row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tbl_dic_value
	 *
	 * @mbg.generated Sun Mar 24 23:53:46 JST 2024
	 */
	int updateByPrimaryKey(DicValue row);

	/**
	 * 根据typeCode来查询数据字典值
	 * 
	 * @param typeCode
	 * @return
	 */
	List<DicValue> selectDicValueByTypeCode(String typeCode);

}