package com.bjpowernode.crm.settings.mapper;

import java.util.List;
import java.util.Map;

import com.bjpowernode.crm.settings.domain.User;

public interface UserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tbl_user
	 *
	 * @mbg.generated Thu Feb 15 16:07:05 JST 2024
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tbl_user
	 *
	 * @mbg.generated Thu Feb 15 16:07:05 JST 2024
	 */
	int insert(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tbl_user
	 *
	 * @mbg.generated Thu Feb 15 16:07:05 JST 2024
	 */
	int insertSelective(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tbl_user
	 *
	 * @mbg.generated Thu Feb 15 16:07:05 JST 2024
	 */
	User selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tbl_user
	 *
	 * @mbg.generated Thu Feb 15 16:07:05 JST 2024
	 */
	int updateByPrimaryKeySelective(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tbl_user
	 *
	 * @mbg.generated Thu Feb 15 16:07:05 JST 2024
	 */
	int updateByPrimaryKey(User row);

	/**
	 * 
	 * 根据账号和密码查询数据
	 * 
	 * @param map
	 * @return
	 */
	User selectUserByLoginActAndPwd(Map<String, Object> map);

	/**
	 * 查询所有的用户
	 * 
	 * @return
	 */
	List<User> selectAllUsers();
}